services:
  - type: web
    name: rizbackoffice
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        sync: false
    plan: free
